[package]
name = "bincode"
version = "0.9.2"
authors = ["Ty Overby <ty@pre-alpha.com>", "Francesco Mazzoli <f@mazzo.li>", "David Tolnay <dtolnay@gmail.com>", "Daniel Griffen"]
exclude = ["logo.png", "tests/*", "examples/*", ".gitignore", ".travis.yml", "changelist.org"]

# renamed `read_types` to `read`
publish = false

repository = "https://github.com/TyOverby/bincode"
documentation = "https://docs.rs/bincode"
readme = "./readme.md"
categories = ["network-programming"]
keywords = ["binary", "encode", "decode", "serialize", "deserialize"]

license = "MIT"
description = "A binary serialization / deserialization strategy that uses Serde for transforming structs into bytes and vice versa!"

[dependencies]
byteorder = "1.0.0"
serde = "1.0.16"

[dev-dependencies]
serde_bytes = "0.10.*"
serde_derive = "1.0.16"

