[workspace]
members = [
    "derive"
]

[package]
name = "bincode"
version = "2.0.0-dev" # remember to update html_root_url and bincode_derive
authors = ["Ty Overby <ty@pre-alpha.com>", "Francesco Mazzoli <f@mazzo.li>", "Zoey Riordan <zoey@dos.cafe>"]
exclude = ["logo.png", "examples/*", ".gitignore", ".github/"]

publish =  true

repository = "https://github.com/bincode-org/bincode"
documentation = "https://docs.rs/bincode"
readme = "./readme.md"
categories = ["encoding", "network-programming"]
keywords = ["binary", "encode", "decode", "serialize", "deserialize"]

license = "MIT"
description = "A binary serialization / deserialization strategy for transforming structs into bytes and vice versa!"

edition = "2018"

[features]
default = ["std"]
std = []
alloc = []

[dependencies]
bincode_derive = { path = "derive", version = "2.0.0-dev" }
# serde = { version = "1.0.130", optional = true }
