[package]
name = "bincode"
version = "1.0.0-alpha1"
authors = ["Ty Overby <ty@pre-alpha.com>", "Francesco Mazzoli <f@mazzo.li>", "David Tolnay <dtolnay@gmail.com>", "Daniel Griffen"]

repository = "https://github.com/TyOverby/bincode"
documentation = "https://docs.rs/bincode"
keywords = ["binary", "encode", "decode", "serialize", "deserialize"]

license = "MIT"
description = "A binary serialization / deserialization strategy and implementation with serde and rustc-serialize backends."

[dependencies]
byteorder = "1.0.0"
num-traits = "0.1.32"

[dependencies.serde]
version = "0.9.*"

[dev-dependencies]
serde_derive = "0.9.*"
