[package]
name = "bincode"
version = "1.1.3" # remember to update html_root_url
authors = ["Ty Overby <ty@pre-alpha.com>", "Francesco Mazzoli <f@mazzo.li>", "David Tolnay <dtolnay@gmail.com>", "Daniel Griffen"]
exclude = ["logo.png", "tests/*", "examples/*", ".gitignore", ".travis.yml"]

publish =  true

repository = "https://github.com/TyOverby/bincode"
documentation = "https://docs.rs/bincode"
readme = "./readme.md"
categories = ["encoding", "network-programming"]
keywords = ["binary", "encode", "decode", "serialize", "deserialize"]
build = "build.rs"

license = "MIT"
description = "A binary serialization / deserialization strategy that uses Serde for transforming structs into bytes and vice versa!"

[dependencies]
byteorder = "1.3.0"
serde = "1.0.63"

[dev-dependencies]
serde_bytes = "0.11"
serde_derive = "1.0.27"

[build-dependencies]
autocfg = "0.1"

[features]
# This feature is no longer used and is DEPRECATED. This crate now
# automatically enables i128 support for Rust compilers that support it. The
# feature will be removed if and when a new major version is released.
i128 = []

[badges]
travis-ci = { repository = "TyOverby/bincode" }
