[workspace]
members = ["derive", "compatibility"]

[package]
name = "bincode"
version = "2.0.0-rc.3" # remember to update html_root_url and bincode_derive
authors = [
    "Ty Overby <ty@pre-alpha.com>",
    "Zoey Riordan <zoey@dos.cafe>",
    "Victor Koenders <bincode@trangar.com>",
]
exclude = ["logo.svg", "examples/*", ".gitignore", ".github/"]

publish = true

repository = "https://github.com/bincode-org/bincode"
documentation = "https://docs.rs/bincode"
readme = "./readme.md"
categories = ["encoding", "network-programming"]
keywords = ["binary", "encode", "decode", "serialize", "deserialize"]

license = "MIT"
description = "A binary serialization / deserialization strategy for transforming structs into bytes and vice versa!"

edition = "2021"

[features]
default = ["std", "derive"]
std = ["alloc", "serde?/std"]
alloc = ["serde?/alloc"]
derive = ["bincode_derive"]

[dependencies]
bincode_derive = { path = "derive", version = "2.0.0-rc.3", optional = true }
serde = { version = "1.0", default-features = false, optional = true }

# Used for tests
[dev-dependencies]
serde_derive = "1.0"
serde_json = { version = "1.0", default-features = false }
tempfile = "3.2"
criterion = "0.3"
rand = "0.8"
uuid = { version = "1.1", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
glam = { version = "0.24", features = ["serde"] }
bincode_1 = { version = "1.3", package = "bincode" }
serde = { version = "1.0", features = ["derive"] }

[[bench]]
name = "varint"
harness = false

[[bench]]
name = "inline"
harness = false

[[bench]]
name = "string"
harness = false

[profile.bench]
codegen-units = 1
debug = 1
lto = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
